language: python
python:
- 3.6
git:
  depth: false
services:
- docker
jobs:
  include:
  - stage: build chart and publish
    install:
    - pip3 install -r dev-requirements.txt
    - mkdir -p bin
    - curl -ssL https://storage.googleapis.com/kubernetes-helm/helm-v2.3.0-linux-amd64.tar.gz
      | tar -xz -C . --strip-components 1 linux-amd64/helm
    - chmod +x helm
    - sudo mv helm /usr/local/bin
    - helm init --client-only
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - CHARTPRESS_OPT=""
    - if [ "x$TRAVIS_TAG" != "x" ]; then CHARTPRESS_OPT="$CHARTPRESS_OPT --tag $TRAVIS_TAG"; fi
    - if [ "x$TRAVIS_COMMIT_RANGE" != "x" ]; then CHARTPRESS_OPT="$CHARTPRESS_OPT --commit-range $TRAVIS_COMMIT_RANGE"; fi
    - chartpress $CHARTPRESS_OPT --push --publish-chart
env:
  global:
  - secure: fKBnv3XANDFnPsazrbGhuJKlenalXl7JyBY7KHioyFLidGPXXMrbz2x2zjvdHYL0lfNtY+Oqi9k7Ho1h2SOxNkXfEemnY7wVMzJs99zjSo795EKpcYGm6chKxFFhmyJDEwVM6ZZOiu+Ostf0+5Ht+6hdK4X/2xMU/MvSunJD/oFoNKWtL1JqdGLVJTeMR/g9z7lS8wuNsTR7B1q3W1mRKMFSgzSM/zMEUBkvrWD34H0NusQisCTTKILOMHrvE/XFfkz0EU8cGyJ6punO8OpduduF8XoxB+o/3ViYHkVVtcA+/lpJ03uJs4GJpOPuC9hBIj22Lyt00Mcofei/uZsEfrl83UI7SxUcymbooUH4RUjIZ4I8vktXORBiVQZ5uB8K/ElKHKXJT1PlWISVFgDa3RC9sKRfVQf1uMDoMS0oIqsRA231u6SGuFz3YmmvLipR/2xIEX3SHiLfGn7a/KnJI2O+jHFMC5JJUEnvVxqbhlwAjFCUwRnMXWH0TNNQCDlcBnh20blc5M82Q9Js2LPKanHR45TGBVJPlWBb9LbzNeaVA6oPAvqi8WnjAPmm76aXE5WQL0A/hwLYbya0D58cJA3QDO/+lagLcfCb2WRF3c0ZWrM8c3LdzLgVZ1kD6T+wCgrs2SSGpgIptWJwlN23ae16wTrfiB6eUaO1FBmSKxA=
  - secure: imXPBYgPvNR6/VE0XcbCxEAKa2ckdIEZqUjQQZzIR7x455pgiZa5F/RhHRlQSa2PdpuZJyxN0HGGRbWCriKWql2EUlT8TxarFR4X8CQay74y+0L6wrjUjlxfqyoSqPIeJh5zdy3Lz/UTeS+7HdqVDAHVdgzYX9SKjPgwOdXSRetO18gjUCA22o+mMTySbtawvg+uZWdd0IEOZZZHu48tmpivljzurJGdezHJueuvdz4SfMj2dOHVbvu7ymGlyIs8hrcC6B062+/4ekTwZ0+CUhn6QW/ORNGvV0rdHPfiMR7+iUVjQR7vXC0mUEDKMqe6EZDBsB3nW756O4vizoqqKPIyABAzKTlGLlTjs7EMKcTNy+KmiLdpor2YfGCPoqhLinqugenyXyS2aB06k1wB+s/e8C6KK6z6nCfJ8Q9OSsKhiXaPNk5PxTM5oZ00QFU0yHoQVxqW2ob/4Yvm6z6PxnofRvzOxdo+PGa+WTBg4QQZ9qGdhiJ4F+ePbDujDHJ+4Oqh7QqGSnkX8GT7gupCHzo4ZAh5UMDEgW78e99A0XSoVTrw6+BQoLO2JRwQRUYjGyK+0DCnTHTwQCNfiRaqQLzR59GTKA2cNcO6pTdtkYAjfdG99g3W+gnb5+3KYsmZfDRb/EbfpsUO/brH83M2fXjuY41BcsnoFADE5Z22rck=
  - secure: adb7o2Xs5MBwaN+8zKXDsA+aFrDQVS1cHiCdqZKZqDa8jtSyicfhmDUbT+TLh5RCTkb6SDmTd6TOZeGJyxZAa4cqeSCytEs2K4UsEMoTOdBZH6bqhrO8+aIG0IqaNgfKZ9eknGCQwJoajyZBzTFsizL1B3lQND2TO18cYPN2Xrxh0pmNQyQ0uaNlswRQ0ltCLOEZHQaiK44HgjWDz6WekYKnJIIDaHFUirgi2SvjQN/hsH6/rs0kTNzgIq4N4dC0TRmYbbDaan5JwDLZ+WC721ts88pWAdcmMvoeJtgsBJKUc9o2U+Ie+SDexDwWos9O9Mwh5ytttWoC9gtCEpFckFINza4oKJSDaiDmN1yQyuusol6afJ0slN/KSJzaYFclJIxz2YuglFmeCDnmHvlUsqgT2JNKjyp4TsSrJMMAgLhL4FqDGFAOsvk/4qojvufK6eURdGC0VZIR1T89AMGgaRMmJ3wNy5Mk/gvAPuB9HgMKtG4vaMci+kow8PGETP/CRbNxwU/oSqZTCz39UKfatb+LFQ8RG1Q57OD0wM8EYyzGGteszCAcG43PCOKmOvsp716QNYIJwlQTDyN1PVSQgttJou+7PHNV4eF63j4hoO3KGGaV+Kjj0oQmm2qzsNV6c65sMFBeBsDmclrFRNGYiXqpeYLe28SqAM9gHpXY54E=
