language: python
python:
- 3.6
git:
  depth: false
services:
- docker
jobs:
  include:
  - stage: build chart and publish
    install:
    - pip3 install -r dev-requirements.txt
    - mkdir -p bin
    - curl -ssL https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz
      | tar -xz -C . --strip-components 1 linux-amd64/helm
    - chmod +x helm
    - sudo mv helm /usr/local/bin
    script:
    - black --check .
    - CHARTPRESS_OPT=""
    - if [ "x$DOCKER_USERNAME" != "x" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; CHARTPRESS_OPT="$CHARTPRESS_OPT --push --publish-chart"; fi
    - if [ "x$TRAVIS_TAG" != "x" ]; then CHARTPRESS_OPT="$CHARTPRESS_OPT --tag $TRAVIS_TAG"; fi
    - mkdir /tmp/foo; helm package notebooks-monitor --dependency-update --destination /tmp/foo
    - chartpress $CHARTPRESS_OPT
