hub:
  services:
    status:
      user: monitor
      apiToken:

monitor:
  worker:
    debug: false
    timeout: 600
    image:
      name: eginotebooks/svc-monitor-mon
      tag: '0.1.0-449ed3b'
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128M
      requests:
        cpu: 100m
        memory: 128M

  ui:
    image:
      name: eginotebooks/svc-monitor-web
      tag: '0.1.0-135ad7a'
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128M
      requests:
        cpu: 100m
        memory: 128M
