---
hub:
  baseUrl: /
  services:
    status:
      user: monitor
      url: "http://status-web/"

monitor:
  # the name of the service in the hub
  serviceName: status
  worker:
    # this can be either jupyterhub or binderhub
    serviceType: jupyterhub
    debug: false
    timeout: 600
    image:
      name: registry.egi.eu/vo.notebooks.egi.eu/svc-monitor-worker
      tag: ""
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128M
      requests:
        cpu: 100m
        memory: 128M

  ui:
    image:
      name: registry.egi.eu/vo.notebooks.egi.eu/svc-monitor-ui
      tag: ""
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128M
      requests:
        cpu: 100m
        memory: 128M
