---
hub:
  services:
    status:
      user: monitor

monitor:
  worker:
    # this can be either jupyterhub or binderhub
    serviceType: jupyterhub
    secret:
      name: hub
      key: hub.services.status.apiToken
    debug: false
    timeout: 600
    image:
      name: registry.egi.eu/vo.notebooks.egi.eu/svc-accounting-monitor
      tag: ""
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128M
      requests:
        cpu: 100m
        memory: 128M

  ui:
    image:
      name: registry.egi.eu/vo.notebooks.egi.eu/svc-monitoring-ui
      tag: ""
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 128M
      requests:
        cpu: 100m
        memory: 128M
