---
apiVersion: v1
kind: Service
metadata:
  name: status-web
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: '{{ template "notebook-monitor.name" . }}'
    chart: '{{ template "notebook-monitor.chart" . }}'
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: hubmonitor
    release: "{{ .Release.Name }}"
